name = "emo-remote-relay"
main = "src/index.js"
compatibility_date = "2025-01-01"

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "PetRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PetRoom"]
